Updated boilerplates
sindresorhus/awesome-electron pull request #693
Opened 2021-05-04 04:25 UTC by reZach

**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

There are a number of boilerplates that are running old versions of Electron that are [not currently supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions). It is better that the community use maintained templates such that best-practices are followed in new Electron apps. I have no authority to _remove_ them, so I thought it would make sense to put them under a **Outdated** header.

Additionally, [vite-electron-builder](https://github.com/cawa-93/vite-electron-builder) (Vue; 167 stars) seems to be a good substitute to the already-existing [electron-vue](https://github.com/SimulatedGREG/electron-vue) which doesn't seem as maintained.

A good majority of Electron frameworks were recently [reviewed by me](https://github.com/reZach/secure-electron-template/wiki/State-of-Electron-frameworks-%5BMay-2021%5D) and I thought my findings could find a place on this repo.

Also, _minor_ css fix as my linter was complaining viewing the readme 👍 .

2021-05-04 11:13 UTC, sindresorhus requested changes

2021-05-04 11:13 UTC, sindresorhus commented on readme.md
> -- [generator-electron](https://github.com/sindresorhus/generator-electron) - Scaffold out an app boilerplate.
These two are maintained. I just updated both of them.

2021-05-04 11:13 UTC, sindresorhus commented on readme.md
> +- [electron-next-skeleton](https://github.com/leo/electron-next-skeleton) - Boilerplate to build your app with Next.js.
I prefer to just remove unmaintained ones rather than having an outdated list.

2021-05-05 03:04 UTC, reZach commented
Thanks for your comments @sindresorhus, I've addressed both of your comments.

2021-05-05 15:40 UTC, merged